name: deploy

on:
  push:
    branches:
      - main   # or "master" if that's your default branch

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          username: cms                          # your server username
          server: panel.cmschlosser.com           # replace with your panel hostname or IP
          port: 22                               # default SSH port
          ssh_private_key: ${{ secrets.SFTP_KEY }}
          local_path: ./                         # deploy everything from repo root
          remote_path: /home/cms/web/awards.cmschlosser.com/public_html
